### ISSUE TITLE
Should not set/use a default password for apt-acng

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-apt#15]
Providing default passwords is not such a good idea. We should force the admin to choose some password (even if he chooses "password" then). Best would be to not provide a default and *fail and stop processing this host* if the password is not supplied. 

Implementation:
* Change default to `""` (empty string) in https://github.com/htgoebel/ansible-apt/blob/master/defaults/main.yml#L91
* Remove fall back to default in https://github.com/htgoebel/ansible-apt/blob/master/templates/etc/apt-cacher-ng/security.conf.j2#L12 (these are useless anyway, because defaults are ensured to be defined in `defaults/main.yml`)
* Add a `fail` in https://github.com/htgoebel/ansible-apt/blob/master/tasks/configure_acng_server.yml#L5.

**Comment by drybjed** [comment]
There's always an option to specify password via `debops.secret` role. :-) `debops.apt` is old and needs an overhaul. `apt-cacher-ng` should be moved to a separate role.

**Comment by ypid** [comment]
Issue is long solved :wink: Check [debops.apt_cacher_ng](https://github.com/debops/ansible-apt_cacher_ng). Anyone wants to close this?
