### ISSUE TITLE
Allow custom Acquire::*::Proxy DIRECT rules

### ISSUE THREAD

**Issue by deveth0** [debops/ansible-apt#64]
Hi,
there is already a flat to enable if you want to bypass your proxy for bugs.debian.org:
apt__proxy_bypass_for_bugs_debian_org

It would be helpful to give the admin the chance to add custom URLs for other bypass options. 
E.g. it's required to add a bypass for download.oracle.com if you want to use the Java8 Installer provided by webupd8:
http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html
http://askubuntu.com/questions/195297/install-oracle-java7-installer-through-apt-cacher-ng

**Comment by ypid** [comment]
Sounds good. Want to implement it?
