### ISSUE TITLE
It should be possible to configure both http and https proxy

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-apt#70]
With apt__proxy_url you can either configure an http_proxy or an https_proxy but not both. If you have both http (regular debiab repo's) and https repositories (eg. docker__upstream_repository is configured to be https), it will not be possible to update from all repositories. 

Propose to add apt__http_proxy_url and apt__https_proxy_url instead of apt__proxy_url.

**Comment by drybjed** [comment]
Sounds good. :+1:

**Comment by tallandtree** [comment]
Ok, I'll implement it.
