### ISSUE TITLE
Basic support for Devuan

### ISSUE THREAD

**Issue by evilham** [debops/ansible-apt#94]
Devuan (https://devuan.org/) is a Debian fork without Systemd.

They name releases after planets, the first release (and currently the only one) is called `jessie` (planet nr.10464) and is, indeed, based after Debian jessie.

It follows the same release model as Debian (jessie = stable, ascii = testing, ceres = unstable).

Adding support for Devuan in ansible-apt means that all common roles get executed against Devuan jessie without issues. (PR incoming)

**Comment by drybjed** [comment]
Sounds fine to me. However, that means that roles which support only `systemd` init with custom service units will need to provide the `sysvinit` init scripts as well, correct? And existing support for SysVinit present in the roles shouldn't be removed, either... Well, let's see how it goes.

**Comment by evilham** [comment]
Yes, I think keeping a `systemd` independent core is a laudable goal. With the roles in `common` and the CLI tools, `debops` is already very useful :-), so I don't think it'd be that much of a problem if some roles don't quite work with devops.
It's worth a try though, as you said: we'll see how it goes!

**Comment by evilham** [comment]
I'll close this issue, since with this merge, it's already possible to just run `debops`, use the core and try out other roles / own playbooks. Since support is not official, it's OK if some things are broken.
